### ISSUE TITLE
How do I build the smartcam firmware files?

### ISSUE THREAD

**Issue by ioindustries** [Xilinx/kv260-firmware#4]
Hello! Are there instructions somewhere for how to build the smartcam firmware in this [repo](https://github.com/Xilinx/kria-apps-firmware/tree/xlnx_rel_v2021.1/smartcam)?

I attempted to generate the kv260-smartcam.dtsi by using xsct and hsi instructions [here](https://github.com/Xilinx/Vitis-Tutorials/blob/2021.1/Vitis_Platform_Creation/Design_Tutorials/01-Edge-KV260/step2.md#generate-device-tree-overlay) along with the xsa that I built from the [kv260_ispMipiRx_vcu_DP](https://github.com/Xilinx/kria-vitis-platforms/tree/release-2021.1/platforms/vivado/kv260_ispMipiRx_vcu_DP) platform but it appears to be missing many components when compared to the kv260-smartcam.dtsi from this repo. Are the dtsi generation steps from that tutorial not enough to recreate the dtsi from this repo?

I'm also unsure how the kv260-smartcam.bit and the kv260-smartcam.xclbin are generated. Are they built from a Vitis project that is available somewhere? Thanks.

**Comment by chkohn** [comment]
@ioidev 

the bit file and the xclbin file are outputs of building the smartcam overlay Vitis project from this repo: https://github.com/Xilinx/kria-vitis-platforms/tree/release-2021.1 . See instructions here: https://xilinx.github.io/kria-apps-docs/main/build/html/docs/build_accel.html

The dtsi file in this example is written by hand based on the hw design and the dt bindings documentation in the linux kernel repo. You can also generate the dtsi but as you noticed, it won't be complete as device tree generator is not aware of board components for example. Instead of using hsi, you can also use the yocto fpgamanager_dtg class (which calls device tree generator under the hood) to generate a dtsi from an xsa but it will have the same deficiencies. The flow is outlined here: https://xilinx.github.io/kria-apps-docs/main/build/html/docs/build_petalinux.html#add-new-fpga-firmware

**Comment by chkohn** [comment]
Marking issue as closed
